import { useState } from 'react';
import { motion } from 'framer-motion';

const projects = [
  {
    id: 1,
    title: "DataScope",
    stack: ["Python", "Pandas", "Matplotlib", "Excel"],
    shortDesc: "End-to-end student performance analysis pipeline. Cleaned and normalized 500+ records.",
    fullDesc: "Ingested raw academic datasets, cleaned and normalized 500+ records, and generated a 12-chart insight dashboard revealing key dropout risk factors.",
    status: "Personal Project",
    github: "#",
    live: "#"
  },
  {
    id: 2,
    title: "PredictIQ",
    stack: ["Python", "Scikit-learn", "NumPy", "Jupyter"],
    shortDesc: "Binary classification model to predict student exam outcomes with 82% accuracy.",
    fullDesc: "Applied feature engineering, cross-validation, and hyperparameter tuning to optimize a Random Forest pipeline for predicting academic success.",
    status: "ML Mini Project",
    github: "#",
    live: "#"
  },
  {
    id: 3,
    title: "PulseBI",
    stack: ["Power BI", "SQL", "Excel"],
    shortDesc: "Interactive business intelligence dashboard for a mock e-commerce dataset.",
    fullDesc: "Built 6 KPI panels, drill-through filters, and time-series trend analysis to simulate real analyst deliverables and optimize business reporting.",
    status: "Data Analytics Project",
    github: "#",
    live: "#"
  },
  {
    id: 4,
    title: "NeuralNotes",
    stack: ["Python", "Flask", "HTML/CSS", "JS"],
    shortDesc: "AI-powered note summarization web app utilizing NLP pipelines.",
    fullDesc: "Users paste lecture notes and receive a bullet-pointed summary, key terms extraction, and a 3-question quiz generated by an NLP pipeline.",
    status: "In Progress",
    github: "#",
    live: "#"
  },
  {
    id: 5,
    title: "MarketMind",
    stack: ["Python", "Pandas", "Plotly", "Scikit-learn"],
    shortDesc: "Stock price trend prediction prototype using 3 years of historical data.",
    fullDesc: "Implemented LSTM-inspired feature windows and produced interactive Plotly visualizations for exploratory analysis of financial data.",
    status: "Research Prototype",
    github: "#",
    live: "#"
  }
];

const ProjectCard = ({ project, index }) => {
  const [isFlipped, setFlipped] = useState(false);

  return (
    <motion.div 
      initial={{ opacity: 0, y: 50 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.6, delay: index * 0.1 }}
      className="w-full aspect-[4/5] sm:aspect-auto sm:h-[400px] perspective-1000"
    >
      <div 
        className={`relative w-full h-full transition-all duration-700 preserve-3d group ${isFlipped ? 'rotate-y-180' : ''}`}
      >
        
        {/* FRONT */}
        <div className="absolute inset-0 w-full h-full backface-hidden bg-slate-900 border border-slate-800 p-6 flex flex-col hover:border-cyan hover:shadow-[0_0_20px_rgba(0,245,212,0.15)] transition-all duration-300">
          
          <div className="absolute top-4 right-4 pointer-events-none">
            <div className="border border-red-500 text-red-500 font-mono text-[10px] sm:text-xs font-bold px-2 py-0.5 transform -rotate-6 opacity-80 uppercase tracking-widest">
              CLASSIFIED
            </div>
          </div>

          <div className="text-violet font-mono text-xs mb-2 mt-4">{`FILE_0${project.id}`}</div>
          <h3 className="font-syne text-2xl font-bold text-white mb-4 line-clamp-1">{project.title}</h3>
          
          <p className="font-mono text-sm text-slate-400 mb-6 flex-grow line-clamp-3">
            {project.shortDesc}
          </p>

          <div className="flex flex-wrap gap-2 mb-6">
            {project.stack.map(tech => (
              <span key={tech} className="px-2 py-1 bg-cyan/10 border border-cyan/30 text-cyan font-mono text-[10px] rounded-full">
                {tech}
              </span>
            ))}
          </div>

          <button 
            onClick={() => setFlipped(true)}
            className="mt-auto flex items-center justify-between w-full py-3 px-4 bg-slate-800 text-slate-200 font-mono text-sm group-hover:bg-cyan/10 group-hover:text-cyan transition-colors"
          >
            <span>[DECLASSIFY]</span>
            <span className="transform group-hover:translate-x-1 transition-transform">→</span>
          </button>
        </div>

        {/* BACK */}
        <div 
          onClick={() => setFlipped(false)}
          className="absolute inset-0 w-full h-full backface-hidden rotate-y-180 bg-slate-900 border border-violet p-6 flex flex-col shadow-[0_0_20px_rgba(139,92,246,0.15)] cursor-pointer group-hover:border-cyan transition-colors"
        >
          
          <div className="flex justify-between items-center mb-6 pointer-events-none">
            <span className="font-mono text-xs text-cyan border border-cyan/30 px-2 py-1">
              STATUS: {project.status.toUpperCase()}
            </span>
            <button 
              className="text-slate-400 hover:text-white font-mono text-sm px-2 pointer-events-auto"
            >
              [X]
            </button>
          </div>

          <h3 className="font-syne text-xl font-bold text-white mb-4 pointer-events-none">{project.title}</h3>
          
          <p className="font-mono text-[13px] sm:text-sm text-slate-300 mb-6 flex-grow leading-relaxed">
            {project.fullDesc}
          </p>

          <div className="flex flex-col gap-3 mt-auto pointer-events-auto">
            <a href={project.live} target="_blank" rel="noopener noreferrer" className="block w-full text-center py-2.5 bg-cyan text-dark font-mono text-sm font-bold tracking-wider hover:bg-white transition-colors" onClick={(e) => e.stopPropagation()}>
              LAUNCH_SYSTEM
            </a>
            <a href={project.github} target="_blank" rel="noopener noreferrer" className="block w-full text-center py-2.5 border border-slate-600 text-slate-300 font-mono text-sm tracking-wider hover:border-violet hover:text-violet transition-colors" onClick={(e) => e.stopPropagation()}>
              SRC_CODE // GITHUB
            </a>
          </div>

        </div>

      </div>
    </motion.div>
  );
};

export default function Projects() {
  return (
    <section className="relative w-full min-h-screen py-24 px-6 md:px-12 lg:px-24 border-b border-slate-900/50 bg-dark z-10">
      <div className="max-w-7xl mx-auto">
        
        <div className="mb-16">
          <h2 className="text-red-500 font-mono text-[11px] tracking-[0.3em] uppercase mb-6 flex items-center gap-4">
            <span className="w-8 h-[1px] bg-red-500/50 block"></span>
            03 / CLASSIFIED FILES
          </h2>
          <h3 className="font-syne text-3xl md:text-5xl font-bold text-white leading-tight">
            Data missions and<br/>architectural prototypes.
          </h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
          {projects.map((proj, idx) => (
            <ProjectCard key={proj.id} project={proj} index={idx} />
          ))}
        </div>

      </div>

      {/* Global CSS for 3D flip since Tailwind utility for preserve-3d/backface-hidden might be missing in default v4 without plugins */}
      <style dangerouslySetInnerHTML={{__html: `
        .perspective-1000 { perspective: 1000px; }
        .preserve-3d { transform-style: preserve-3d; }
        .backface-hidden { backface-visibility: hidden; }
        .-rotate-y-180 { transform: rotateY(-180deg); }
        .rotate-y-180 { transform: rotateY(180deg); }
      `}} />
    </section>
  );
}
